name: Capture JSON Data

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  capture_json_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt
        # Make sure you have a requirements.txt file with 'requests' and 'pandas' listed

      - name: Run Python script
        run: |
          python scripts/01-get_servers.py
          
      - name: commit files
        run: | 
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m "updated records" || echo "no changes to commit"
          git push origin || echo "no changes to commit"
